### ISSUE TITLE
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 35, column 33

### ISSUE THREAD

**Issue by CkkWinkie** [dongfanger/pycnblog#17]
markdown读取成功:/Users/ckk/Desktop/test.md
共找到0张本地图片

无需上传图片
Traceback (most recent call last):
  File "/Users/ckk/Desktop/pycnblog/upload.py", line 61, in <module>
    recent_posts = server.metaWeblog.getRecentPosts(conf["blog_id"], conf["username"], conf["password"], 99)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1123, in __call__
    return self.__send(self.__name, args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1465, in __request
    response = self.__transport.request(
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1167, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1183, in single_request
    return self.parse_response(resp)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1349, in parse_response
    p.feed(data)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 451, in feed
    self._parser.Parse(data, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 35, column 33

测试文件一个图片都没有，单纯上传功能就出现报错
出现该报错该如何解决呢？

**Comment by CkkWinkie** [comment]
哈哈，是我自己写错了url地址，已解决
