### ISSUE TITLE
Traceback (most recent call last): 问题 昨天还可以今天一直出错

### ISSUE THREAD

**Issue by Xinchenlove** [dongfanger/pycnblog#19]
出错内容 如下 pyyaml也安装了 重启电脑没有效果

Traceback (most recent call last):
  File "D:\博客园上传\pycnblog-master\upload.py", line 7, in <module>
    from img_transfer import *
  File "D:\博客园上传\pycnblog-master\img_transfer.py", line 4, in <module>
    from config_loader import conf
  File "D:\博客园上传\pycnblog-master\config_loader.py", line 11, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by Xinchenlove** [comment]
前两天还是不行，重装python也不行，今天突然又行了

**Comment by dongfanger** [comment]
又行了就行
